version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    post_build:
      commands:
        - mvn package
artifacts:
  files:
    - target/learningdiary-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
  eb_codebuild_settings:
    CodeBuildServiceRole: AWSCodePipelineServiceRole-eu-west-1-nooran-ld-pipeelini
    ComputeType: BUILD_GENERAL1_SMALL
    Image: aws/codebuild/standard:2.0
    Timeout: 60