version: 0.2

phases:
  build:
    commands: echo "Building"
  post_build:
    commands:
      - echo "Build successfull!"
      - mvn package
      - mv target/learningdiary-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/*.jar