version: 0.2

phases:
  install:
    commands:
      - echo "Installing maven"
      - apt-get install -y maven
      - apt-get update -y
  build:
    commands: echo "Building"
  post_build:
    commands:
      - echo "Build successfull!"
      - mvn package
      - mv target/learningdiary-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/*.jar
    - maven.yml