version: 0.2

phases:
  install:
    commands:
      - echo "Installing maven"
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo "Building"
  post_build:
    commands:
      - echo "Build successfull!"
      - mvn package
      - mv target/.jar
artifacts:
  files:
    - target/.jar
    - .ebextensions/*/
    - appsepc.yml
    - apt-get update -y
      - apt-get install -y maven